### ISSUE TITLE
🎨 中優先度: UI/UX大幅改善とアクセシビリティ対応

### ISSUE THREAD

**Issue by nyasuto** [nyasuto/murmur#31]
### **優先度: 中**
**影響:** ユーザー体験、アクセシビリティ  
**コンポーネント:** フロントエンド全体  
**ファイル:** `renderer/` 配下の全ファイル

#### 1. 視覚的フィードバックの不足
**現在の問題:**
- ローディング状態の表示不備
- 処理中のプログレス表示なし
- エラー状態の視覚的明示不足

#### 2. キーボードナビゲーション未対応
**問題:**
- タブキーでの操作不可
- ショートカットキーの不足
- フォーカス管理が不適切

#### 3. アクセシビリティ対応不足
**WCAG 2.1準拠の課題:**
- ARIAラベルの欠如
- コントラスト比の不適合
- スクリーンリーダー対応不足

#### 4. レスポンシブデザイン未対応
**問題:**
- モバイルサイズでの表示崩れ
- 異なる画面解像度への未対応
- ウィンドウリサイズ時の挙動不良

#### Phase 1: 基本的なUX改善（Week 1-2）

1. **ローディング・プログレス表示**
   ```html
   <\!-- 新規コンポーネント -->
   <div class="progress-container" id="progressContainer">
     <div class="progress-bar">
       <div class="progress-fill" id="progressFill"></div>
     </div>
     <div class="progress-text" id="progressText">処理中...</div>
   </div>
   ```

   ```javascript
   class ProgressManager {
     show(message, percentage = 0) {
       this.container.classList.remove('hidden');
       this.updateProgress(percentage, message);
     }
     
     updateProgress(percentage, message) {
       this.fill.style.width = `${percentage}%`;
       this.text.textContent = message;
     }
   }
   ```

2. **エラー状態の改善**
   ```css
   .error-state {
     background: #fee2e2;
     border: 1px solid #fca5a5;
     border-radius: 8px;
     padding: 16px;
     color: #991b1b;
   }
   
   .success-state {
     background: #dcfce7;
     border: 1px solid #86efac;
     border-radius: 8px;
     padding: 16px;
     color: #166534;
   }
   ```

3. **キーボードショートカット**
   ```javascript
   // 追加するショートカット
   const shortcuts = {
     'Space': 'toggleRecording',      // スペース: 録音開始/停止
     'Escape': 'cancelOperation',     // Esc: 操作キャンセル
     'Ctrl+S': 'saveToObsidian',     // Ctrl+S: 保存
     'Ctrl+Delete': 'clearContent',   // Ctrl+Del: クリア
     'F1': 'showHelp'                // F1: ヘルプ表示
   };
   ```

#### Phase 2: アクセシビリティ対応（Week 2-3）

1. **ARIAラベルの実装**
   ```html
   <button 
     id="recordButton" 
     aria-label="音声録音を開始"
     aria-describedby="recordingStatus"
     role="button">
     <span class="record-icon" aria-hidden="true">🎙️</span>
     <span class="record-text">録音開始</span>
   </button>
   
   <div id="recordingStatus" aria-live="polite" aria-atomic="true">
     <\!-- 録音状態のライブ更新 -->
   </div>
   ```

2. **フォーカス管理**
   ```javascript
   class FocusManager {
     trapFocus(container) {
       const focusableElements = container.querySelectorAll(
         'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
       );
       
       // フォーカストラップロジック
     }
     
     restoreFocus(previousElement) {
       if (previousElement) {
         previousElement.focus();
       }
     }
   }
   ```

3. **スクリーンリーダー対応**
   ```javascript
   class ScreenReaderAnnouncer {
     announce(message, priority = 'polite') {
       const announcer = document.createElement('div');
       announcer.setAttribute('aria-live', priority);
       announcer.setAttribute('aria-atomic', 'true');
       announcer.textContent = message;
       
       document.body.appendChild(announcer);
       setTimeout(() => document.body.removeChild(announcer), 1000);
     }
   }
   ```

#### Phase 3: レスポンシブデザイン（Week 3-4）

1. **グリッドレイアウトの実装**
   ```css
   .app-container {
     display: grid;
     grid-template-areas: 
       "header header"
       "controls status"
       "results results";
     grid-template-columns: 1fr 300px;
     gap: 16px;
   }
   
   @media (max-width: 768px) {
     .app-container {
       grid-template-areas: 
         "header"
         "controls"
         "status"
         "results";
       grid-template-columns: 1fr;
     }
   }
   ```

2. **フルイドタイポグラフィ**
   ```css
   .text-responsive {
     font-size: clamp(14px, 2.5vw, 18px);
     line-height: 1.5;
   }
   ```

#### Phase 4: 高度なUX機能（Week 4-5）

1. **ダークモード対応**
   ```css
   :root {
     --bg-primary: #ffffff;
     --text-primary: #1f2937;
     --accent-color: #3b82f6;
   }
   
   [data-theme="dark"] {
     --bg-primary: #1f2937;
     --text-primary: #f9fafb;
     --accent-color: #60a5fa;
   }
   ```

2. **アニメーション・トランジション**
   ```css
   .fade-in {
     animation: fadeIn 0.3s ease-in-out;
   }
   
   @keyframes fadeIn {
     from { opacity: 0; transform: translateY(10px); }
     to { opacity: 1; transform: translateY(0); }
   }
   ```

3. **オフライン対応表示**
   ```javascript
   class OfflineIndicator {
     constructor() {
       window.addEventListener('online', () => this.show('オンライン'));
       window.addEventListener('offline', () => this.show('オフライン', 'warning'));
     }
   }
   ```

#### WCAG 2.1準拠チェックリスト
- [ ] **Level A**
  - [ ] 適切な見出し構造（h1-h6）
  - [ ] 画像のalt属性
  - [ ] フォームラベルの関連付け
  - [ ] キーボードナビゲーション

- [ ] **Level AA**  
  - [ ] コントラスト比4.5:1以上
  - [ ] フォーカス表示の明確化
  - [ ] 音声・動画の字幕対応
  - [ ] ページタイトルの意味性

#### CSS最適化
```css
/* Critical CSS の分離 */
.critical {
  /* 初期表示に必要なスタイル */
}

/* Non-critical CSS の遅延読み込み */
.enhanced {
  /* 装飾的なスタイル */
}
```

#### JavaScript最適化
```javascript
// 遅延初期化
class LazyUIEnhancements {
  init() {
    // IntersectionObserver を使用した遅延読み込み
    this.observeVisibility();
  }
}
```

### 受け入れ基準
- [ ] 全ての操作でローディング状態が表示される
- [ ] キーボードのみで全機能が操作可能
- [ ] WCAG 2.1 Level AA に準拠
- [ ] 320px幅から1920px幅まで適切に表示
- [ ] スクリーンリーダーで内容が理解可能
- [ ] ダークモード対応済み
- [ ] オフライン状態の明示

### 検証方法
- [ ] Lighthouse アクセシビリティスコア90+
- [ ] axe-core による自動テスト
- [ ] 実際の視覚障害者によるユーザビリティテスト
- [ ] 複数デバイス・画面サイズでの表示確認

**全てのユーザーにとって使いやすく、アクセシブルなアプリケーションの実現**
