### ISSUE TITLE
Medium: Remove hardcoded Japanese prompts and add internationalization

### ISSUE THREAD

**Issue by nyasuto** [nyasuto/murmur#36]
## Summary
AI text processing prompts are hardcoded in Japanese, limiting multilingual support and making the system less flexible for international users.

## Problem
File: `src/murmur/ai_text_processor.py` lines 102-164

Hardcoded Japanese prompts:
```python
default_prompts = {
    "daily_log": "以下の音声入力を、日記の一部として自然な日本語で整理してください...",
    "meeting_notes": "以下の会議の音声を、構造化されたメモとして整理してください...",
    "task_extraction": "以下のテキストからタスクやアクションアイテムを抽出し...",
    # ... more Japanese prompts
}
```

## Impact
- **Limited to Japanese users only**
- **No internationalization support**
- **Hardcoded business logic in code**
- **Difficult to customize prompts**
- **Prevents localization for global users**

### 1. Externalize Prompts to Configuration
```yaml
# prompts/ja.yaml
daily_log: |
  以下の音声入力を、日記の一部として自然な日本語で整理してください...

meeting_notes: |
  以下の会議の音声を、構造化されたメモとして整理してください...

# prompts/en.yaml  
daily_log: |
  Please organize the following voice input as a natural English diary entry...

meeting_notes: |
  Please organize the following meeting audio as structured notes...
```

### 2. Add Language Detection and Selection
```python
class AITextProcessor:
    def __init__(self, language: str = "auto"):
        self.language = language
        self.prompts = self._load_prompts(language)
    
    def _load_prompts(self, language: str) -> dict:
        if language == "auto":
            language = self._detect_language()
        return load_prompts_for_language(language)
```

### 3. Configuration Structure
```python
@dataclass
class PromptConfig:
    language: str = "ja"
    custom_prompts_dir: Optional[str] = None
    fallback_language: str = "en"
```

### Phase 1: Externalize Current Prompts
- [ ] Create `prompts/` directory structure
- [ ] Move Japanese prompts to `prompts/ja.yaml`
- [ ] Update AITextProcessor to load from files

### Phase 2: Add English Support
- [ ] Create `prompts/en.yaml` with English translations
- [ ] Add language parameter to configuration
- [ ] Implement prompt loading logic

### Phase 3: Add Auto-Detection
- [ ] Integrate with Whisper language detection
- [ ] Add fallback mechanism for unsupported languages
- [ ] Add user preference override

## Acceptance Criteria
- [ ] Prompts externalized to YAML files
- [ ] Support for multiple languages (at least ja, en)
- [ ] Language auto-detection from Whisper results
- [ ] Fallback to default language for unsupported languages
- [ ] User can override language preference
- [ ] Custom prompts directory support
- [ ] Backwards compatibility maintained
- [ ] Documentation for adding new languages

## File Structure
```
prompts/
├── ja.yaml          # Japanese prompts
├── en.yaml          # English prompts
├── zh.yaml          # Chinese prompts (future)
└── template.yaml    # Template for new languages
```

## Priority
Medium - enhances usability but not critical for current users

## Labels
priority: medium, type: enhancement, area: i18n
